name: build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Update Homebrew
        run: |
          brew update --preinstall
          cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/readline.rb" > .github/brew-formulae
      - name: Cache readline
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Caches/Homebrew/readline
            ~/Library/Caches/Homebrew/downloads/readline
          key: brew-${{ hashFiles('.github/brew-formulae') }}
          restore-keys: brew-
      - name: Install readline
        run: |
          env HOMEBREW_NO_AUTO_UPDATE=1 brew install readline
      - name: Export readline
        shell: bash
        run: |
          brew info readline | grep export |
          while read line
          do
            $(echo "$line" | cut -d ' ' -f2 >> $GITHUB_ENV)
          done
      - name: Build
        run: make
